# Generated by Django 5.0.2 on 2024-04-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='kcal',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
